<?php

namespace Guodaolinyi\Flysystem\BaiduBos;


use BaiduBce\Services\Bos\BosClient;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\ServiceProvider;
use League\Flysystem\Filesystem;

class BosStorageServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        Storage::extend('bos', function ($app, $config) {
            $client = new BosClient($config['options']);
            return new Filesystem(new BosAdapter($client, $config['bucket'], $config['prefix'],$config['expire']=''));
        });
    }
}